services:
  ror2-server:
    build: .
    container_name: ror2-server
    ports:
      - "${PORT:-27015}:${PORT:-27015}/udp"
      - "${STEAM_QUERY_PORT:-27016}:${STEAM_QUERY_PORT:-27016}/udp"
      - "${STEAM_SERVER_PORT:-27017}:${STEAM_SERVER_PORT:-27017}/udp"
    # IMPORTANT: it is NOT an option for WSL hosts, since it breaks wine. On WSL, you have to build /game/ into the image.
    # volumes:
    #   - ./Risk of Rain 2/:/game/
    environment:
      - MAX_PLAYERS=${MAX_PLAYERS:-4}
      - STEAM_HEARTBEAT=${STEAM_HEARTBEAT:-1}
      - SERVER_HOSTNAME=${SERVER_HOSTNAME:-Risk of Rain 2 Dedicated Server}
      - PORT=${PORT:-27015}
      - STEAM_QUERY_PORT=${STEAM_QUERY_PORT:-27016}
      - STEAM_SERVER_PORT=${STEAM_SERVER_PORT:-27017}
      - SERVER_PASSWORD=${SERVER_PASSWORD:-}
      - SERVER_CUSTOM_TAGS=${SERVER_CUSTOM_TAGS:-}
      - GAMEMODE=${GAMEMODE:-ClassicRun}
      - EXTRA_ARGS=${EXTRA_ARGS:-}
